# Generated by Django 5.1 on 2024-10-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='student',
            new_name='insurance',
        ),
    ]
