# Generated by Django 5.1 on 2024-10-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_rename_student_ticket_insurance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_type',
            new_name='disease',
        ),
    ]
